package com.sist.main;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

public class MainClass정보 {

	public static void main(String[] args) {
		String html = "\r\n"
				+ "<!DOCTYPE html>\r\n"
				+ "<html lang=\"ko\">\r\n"
				+ "<head>\r\n"
				+ "<!-- META -->\r\n"
				+ "<meta charset=\"utf-8\">\r\n"
				+ "<meta name=\"Generator\" content=\"XpressEngine\">\r\n"
				+ "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "<!-- TITLE -->\r\n"
				+ "<title>영사기능사 시험 기출문제 시험일정 응시자격 - 스터디온</title>\r\n"
				+ "<!-- CSS -->\r\n"
				+ "<link rel=\"stylesheet\" href=\"/common/css/xe.css?20170416145744\" />\r\n"
				+ "<link rel=\"stylesheet\" href=\"/common/js/plugins/ui/jquery-ui.css?20120427182804\" />\r\n"
				+ "<link rel=\"stylesheet\" href=\"/layouts/webmini 4.5.5/css/default_user.css?20180614145432\" />\r\n"
				+ "<link rel=\"stylesheet\" href=\"/modules/editor/styles/ckeditor_light/style.css?20170416145851\" />\r\n"
				+ "<link rel=\"stylesheet\" href=\"/widgets/login_info/skins/xgenesis_login/css/black.css?20101005003929\" />\r\n"
				+ "<link rel=\"stylesheet\" href=\"/widgets/menuL/skins/tree/css/widget.css?20171116195858\" />\r\n"
				+ "<link rel=\"stylesheet\" href=\"/widgetstyles/tingenara/css.css?20170416153705\" />\r\n"
				+ "<link rel=\"stylesheet\" href=\"/files/faceOff/554/088/003/layout.css?20171215173748\" />\r\n"
				+ "<!-- JS -->\r\n"
				+ "<!--[if lt IE 9]><script src=\"/common/js/jquery-1.x.js?20170416145742\"></script>\r\n"
				+ "<![endif]--><!--[if gte IE 9]><!--><script src=\"/common/js/jquery.js?20171117233106\"></script>\r\n"
				+ "<!--<![endif]--><script src=\"/common/js/modernizr.js?20170416145742\"></script>\r\n"
				+ "<script src=\"/common/js/x.js?20170416145742\"></script>\r\n"
				+ "<script src=\"/common/js/common.js?20170416145742\"></script>\r\n"
				+ "<script src=\"/common/js/js_app.js?20170416145742\"></script>\r\n"
				+ "<script src=\"/common/js/xml_handler.js?20171118002432\"></script>\r\n"
				+ "<script src=\"/common/js/xml_js_filter.js?20170416145743\"></script>\r\n"
				+ "<script src=\"/layouts/webmini 4.5.5/js/webmini.js?20100702181930\"></script>\r\n"
				+ "<script src=\"/widgets/login_info/skins/xgenesis_login/js/login.js?20100801165543\"></script>\r\n"
				+ "<script src=\"/widgets/menuL/skins/tree/js/navigator.js?20170416151631\"></script>\r\n"
				+ "<!-- RSS -->\r\n"
				+ "<!-- ICON -->\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<script type=\"text/javascript\">  \r\n"
				+ "var _gaq = _gaq || [];  \r\n"
				+ "_gaq.push(['_setAccount', 'UA-18745289-1']); \r\n"
				+ "_gaq.push(['_trackPageview']);  \r\n"
				+ "(function() \r\n"
				+ "{    \r\n"
				+ "var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;    \r\n"
				+ "ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';    \r\n"
				+ "var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);  \r\n"
				+ "}\r\n"
				+ ")();\r\n"
				+ "</script>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "<link rel=\"canonical\" href=\"https://www.studyon.co.kr/index.php?mid=e0098\" />\r\n"
				+ "<meta name=\"keywords\" content=\"기사 기출문제,산업기사 기출문제,기능사 기출문제,국가자격증 기출문제,기술사 기출문제,기능장 기출문제,기사 시험일정,산업기사 시험일정,기능사 시험일정,국가자격증 시험일정,기술사 시험일정,기능장 시험일정,기사 자격증,산업기사 자격증,기능사 자격증,국가 공인 자격증,기술사 자격증,기능장 자격증,기사 요점정리,산업기사 요점정리,기능사 요점정리,국가자격증 요점정리,기술사 요점정리,기능장 요점정리,기사 합격후기,산업기사 합격후기,기능사 합격후기,국가자격증 합격후기,기술사 합격후기,기능장 합격후기,기사 시험 자료,산업기사 시험 자료,기능사 시험 자료,기술사 시험 자료,기능장 시험 자료,국가자격증 시험 자료,자격증 사이트,무료 자격증 사이트,국가자격증 종류,기술자격증 종류,국가기술자격증 종류,국가기술자격증 조회,자격증 공부,국가기술자격증 발급,국가기술자격증 시험,자격증 기출문제 사이트,자격증 공부 도움되는 사이트,자격증 시험 독학,국가자격증,국가기술자격증 일정,국가자격증 시험,국가자격증 시험 한 번에 합격하기\" />\r\n"
				+ "<meta name=\"description\" content=\"기술사/기사/산업기사/기능장/기능사 기출문제, 요점정리, 시험일정, 시험후기 자격증 사이트\" />\r\n"
				+ "<meta property=\"og:locale\" content=\"ko_KR\" />\r\n"
				+ "<meta property=\"og:type\" content=\"website\" />\r\n"
				+ "<meta property=\"og:url\" content=\"https://www.studyon.co.kr/index.php?mid=e0098\" />\r\n"
				+ "<meta property=\"og:site_name\" content=\"스터디온\" />\r\n"
				+ "<meta property=\"og:title\" content=\"영사기능사 시험 기출문제 시험일정 응시자격 - 스터디온\" />\r\n"
				+ "<meta property=\"og:description\" content=\"기술사/기사/산업기사/기능장/기능사 기출문제, 요점정리, 시험일정, 시험후기 자격증 사이트\" />\r\n"
				+ "<style type=\"text/css\">\r\n"
				+ "    body { background:#FFFFFF url(./layouts/webmini 4.5.5//images/default/bg.gif) no-repeat center top; }\r\n"
				+ "	</style><script>\r\n"
				+ "//<![CDATA[\r\n"
				+ "var current_url = \"https://www.studyon.co.kr/?mid=e0098\";\r\n"
				+ "var request_uri = \"https://www.studyon.co.kr/\";\r\n"
				+ "var current_mid = \"e0098\";\r\n"
				+ "var waiting_message = \"서버에 요청중입니다. 잠시만 기다려주세요.\";\r\n"
				+ "var ssl_actions = new Array();\r\n"
				+ "var default_url = \"https://www.studyon.co.kr/\";\r\n"
				+ "var enforce_ssl = true;xe.current_lang = \"ko\";\r\n"
				+ "xe.cmd_find = \"찾기\";\r\n"
				+ "xe.cmd_cancel = \"취소\";\r\n"
				+ "xe.cmd_confirm = \"확인\";\r\n"
				+ "xe.msg_no_root = \"\";\r\n"
				+ "xe.msg_no_shortcut = \"\";\r\n"
				+ "xe.msg_select_menu = \"\";\r\n"
				+ "//]]>\r\n"
				+ "</script>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "<!-- js 파일 import -->\r\n"
				+ "<!--#Meta:layouts/webmini 4.5.5/js/webmini.js--><!-- 레이아웃과 연동될 css 파일 import -->\r\n"
				+ "    <!--#Meta:layouts/webmini 4.5.5/css/default_user.css-->\r\n"
				+ "<script type=\"text/javascript\">\r\n"
				+ "     function showhide(obj) {\r\n"
				+ "     var seogd = document.getElementById(obj);\r\n"
				+ "     var img = document.getElementById('ja_img');\r\n"
				+ "        if ( seogd.style.display != 'none' ) {\r\n"
				+ "            seogd.style.display = 'none';\r\n"
				+ "            img.src = '/image/btn_ja_list.gif';\r\n"
				+ "        } else {\r\n"
				+ "       seogd.style.display = '';\r\n"
				+ "       img.src = '/image/btn_ja_list_on.gif';\r\n"
				+ "       fitHeight();\r\n"
				+ "      }\r\n"
				+ "}\r\n"
				+ "function fitHeight(){\r\n"
				+ "  var obj = document.getElementById(\"ja_menu\");\r\n"
				+ "  if (obj.scrollHeight > 500) {\r\n"
				+ "    obj.style.height = '500px';\r\n"
				+ "    if(!obj.style.width){\r\n"
				+ "      obj.style.width = obj.scrollWidth + 5;\r\n"
				+ "     }\r\n"
				+ "  }\r\n"
				+ "}\r\n"
				+ "</script> \r\n"
				+ "<div id=\"topbg\">\r\n"
				+ "</div>\r\n"
				+ "<div id=\"bodyWrap\">\r\n"
				+ "	<div id=\"header\">\r\n"
				+ "<div id=\"topbg_1\">\r\n"
				+ "</div>\r\n"
				+ "<h1><a href=\"home\"><img src=\"/layouts/webmini 4.5.5/images/default/logo.gif\" alt=\"자격증 커뮤니티 NO.1 스터디온\" title=\"자격증 커뮤니티 NO.1 스터디온\" class=\"iePngFix\" /></a></h1>\r\n"
				+ "				<div id=\"mini_gnb\">\r\n"
				+ "			<ul>\r\n"
				+ "							<div class=\"xe-widget-wrapper \" style=\"display:none\"><div style=\"*zoom:1;padding:0px 0px 0px 0px !important;\">    <script type=\"text/javascript\">\r\n"
				+ "    var keep_signed_msg = \"브라우저를 닫더라도 로그인이 계속 유지될 수 있습니다.\\n\\n로그인 유지 기능을 사용할 경우 다음 접속부터는 로그인할 필요가 없습니다.\\n\\n단, 게임방, 학교 등 공공장소에서 이용 시 개인정보가 유출될 수 있으니 꼭 로그아웃을 해주세요.\";\r\n"
				+ "    xAddEventListener(window, \"load\", function(){ doFocusUserId(\"fo_login_widget\"); });\r\n"
				+ "</script>\r\n"
				+ "<fieldset id=\"login\" class=\"login\">\r\n"
				+ "<legend>로그인</legend>\r\n"
				+ "<form action=\"./\" method=\"get\" onsubmit=\"return procFilter(this, widget_login)\" id=\"fo_login_widget\"><input type=\"hidden\" name=\"error_return_url\" value=\"/e0098\" /><input type=\"hidden\" name=\"act\" value=\"\" /><input type=\"hidden\" name=\"mid\" value=\"e0098\" /><input type=\"hidden\" name=\"vid\" value=\"\" />\r\n"
				+ "    <div class=\"idpwWrap\">\r\n"
				+ "        <div class=\"idpw\">\r\n"
				+ "            <input name=\"user_id\" type=\"text\" title=\"user id\" onfocus=\"this.className='idOn';\" onblur=\"if (!this.value) this.className='idOff'\" class=\"idOff\" />\r\n"
				+ "            <input name=\"password\" type=\"password\" title=\"password\" onfocus=\"this.className='passOn';\" onblur=\"if (!this.value) this.className='passOff'\" class=\"passOff\" />\r\n"
				+ "        </div>\r\n"
				+ "        <input type=\"image\" src=\"/widgets/login_info/skins/xgenesis_login/images/buttonLogin.gif\" alt=\"login\" title=\"login\" class=\"login\" />\r\n"
				+ "    </div>\r\n"
				+ "    <p class=\"save\">\r\n"
				+ "        <input type=\"checkbox\" name=\"keep_signed\" id=\"keepid\" value=\"Y\" onclick=\"return confirm(keep_signed_msg);\" />\r\n"
				+ "        <label for=\"keepid\" title=\"로그인 유지\" >로그인 유지</label>\r\n"
				+ "            </p>\r\n"
				+ "    <ul class=\"help\">\r\n"
				+ "        <li class=\"first-child\"><a href=\"https://www.studyon.co.kr/index.php?mid=e0098&amp;act=dispMemberSignUpForm\" title=\"회원가입\">회원가입</a></li>\r\n"
				+ "        <li><a href=\"https://www.studyon.co.kr/index.php?mid=e0098&amp;act=dispMemberFindAccount\" title=\"ID/PW 찾기\">ID/PW 찾기</a></li>\r\n"
				+ "    </ul>\r\n"
				+ "</form> \r\n"
				+ "</fieldset>\r\n"
				+ "<!-- OpenID -->\r\n"
				+ "<script type=\"text/javascript\">\r\n"
				+ "  xAddEventListener(window, \"load\", function(){ doFocusUserId(\"fo_login_widget\"); });\r\n"
				+ "</script>\r\n"
				+ "</div></div>\r\n"
				+ "<form action=\"./Main_test\" method=\"get\" onsubmit=\"return procFilter(this, widget_login)\" id=\"fo_login_widget\"><input type=\"hidden\" name=\"error_return_url\" value=\"/e0098\" /><input type=\"hidden\" name=\"act\" value=\"\" /><input type=\"hidden\" name=\"mid\" value=\"e0098\" /><input type=\"hidden\" name=\"vid\" value=\"\" />\r\n"
				+ "<script type=\"text/javascript\">\r\n"
				+ "    var keep_signed_msg = \"브라우저를 닫더라도 로그인이 계속 유지될 수 있습니다.\\n\\n로그인 유지 기능을 사용할 경우 다음 접속부터는 로그인을 하실 필요가 없습니다.\\n\\n단, 게임방, 학교 등 공공장소에서 이용 시 개인정보가 유출될 수 있으니 꼭 로그아웃을 해주세요.\";\r\n"
				+ "    xAddEventListener(window, \"load\", function(){ doFocusUserId(\"fo_login_widget\"); });\r\n"
				+ "</script>\r\n"
				+ "<li><a href=\"javascript:window.external.addfavorite('/home', '자격증 커뮤니티 NO.1 스터디온');\"><img src=\"/image/jadd.gif\" border=\"0\" align=\"left\"></a></li>\r\n"
				+ "<li><input type=\"checkbox\" name=\"keep_signed\" id=\"keepid\" value=\"Y\" onclick=\"return confirm(keep_signed_msg);\" /> 로그인 유지 | <a href=\"/index.php?mid=&act=dispMemberFindAccount\" title=\"아이디/비밀번호 찾기\">ID/PW 찾기</a> | <a href=\"/index.php?mid=&act=dispMemberSignUpForm\" title=\"회원 가입\">회원 가입</a> <input name=\"user_id\" type=\"text\" title=\"user id\" onfocus=\"this.className='idOn';\" onblur=\"if (!this.value) this.className='idOff'\" class=\"idOff\" style=\"width:90px;height:13px\" /> <input name=\"password\" type=\"password\" title=\"password\" onfocus=\"this.className='passOn';\" onblur=\"if (!this.value) this.className='passOff'\" class=\"passOff\" style=\"width:90px;height:13px\" /> <input type=\"image\" src=\"/layouts/webmini 4.5.5/images/default/btn_mini_login.gif\" alt=\"login\" title=\"login\" class=\"login\" align=\"absmiddle\"/></li></form>\r\n"
				+ "				                			</ul>\r\n"
				+ "            <!-- 미니메뉴 -->\r\n"
				+ "            <div id=\"minimenu1\" onmouseover=\"divDisplay('1','true')\" onmouseout=\"divDisplay('1','false')\">\r\n"
				+ "                <ul>\r\n"
				+ "                    <li><a href=\"https://www.studyon.co.kr/index.php?mid=e0098&amp;act=dispMemberInfo\">회원정보</a></li>\r\n"
				+ "                    <li><a href=\"https://www.studyon.co.kr/index.php?mid=e0098&amp;act=dispMemberScrappedDocument\">스크랩보기</a></li>\r\n"
				+ "                    <li><a href=\"https://www.studyon.co.kr/index.php?mid=e0098&amp;act=dispMemberSavedDocument\">저장함</a></li>\r\n"
				+ "                    <li><a href=\"https://www.studyon.co.kr/index.php?mid=e0098&amp;act=dispMemberOwnDocument\">작성글보기</a></li>\r\n"
				+ "                    <li><a href=\"https://www.studyon.co.kr/index.php?mid=e0098&amp;act=dispCommunicationFriend\">친구보기</a></li>\r\n"
				+ "                    <li><a href=\"https://www.studyon.co.kr/index.php?mid=e0098&amp;act=dispCommunicationMessages\">쪽지함</a></li>\r\n"
				+ "                </ul>\r\n"
				+ "            </div>\r\n"
				+ "            \r\n"
				+ "		</div>\r\n"
				+ "		\r\n"
				+ "		<!--GNB-->\r\n"
				+ "		<ul id=\"gnb\">\r\n"
				+ "			<!-- main_menu 1차 시작 -->\r\n"
				+ "									<li ><a href=\"https://www.studyon.co.kr/index.php?mid=home\"  title=\"자격증전체보기\">자격증전체보기</a></li>\r\n"
				+ "									<li ><a href=\"https://www.studyon.co.kr/index.php?mid=examschedule\"  title=\"자격증시험일정\">자격증시험일정</a></li>\r\n"
				+ "									<li ><a href=\"https://www.studyon.co.kr/index.php?mid=studyonnews\"  title=\"자격증뉴스\">자격증뉴스</a></li>\r\n"
				+ "									<li ><a href=\"https://www.studyon.co.kr/index.php?mid=eduinfo\"  title=\"추천교육\">추천교육</a></li>\r\n"
				+ "									<li ><a href=\"https://www.studyon.co.kr/index.php?mid=nanumboard\"  title=\"책나눔장터\">책나눔장터</a></li>\r\n"
				+ "									<li ><a href=\"https://www.studyon.co.kr/index.php?mid=total_examfile\"  title=\"자격증시험자료\">자격증시험자료</a></li>\r\n"
				+ "									<li ><a href=\"https://www.studyon.co.kr/index.php?mid=total_gichul\"  title=\"최신기출문제\">최신기출문제</a></li>\r\n"
				+ "						<!-- main_menu 1차 끝 -->\r\n"
				+ "		</ul>\r\n"
				+ "		\r\n"
				+ "			<!-- 상단확장 -->\r\n"
				+ "<div id=\"add_top\"> </div>\r\n"
				+ "<div id=\"gnb_sub\"><span style=\"COLOR: #fd6c46\"><span style=\"FONT-SIZE: 10px\">▶&nbsp;&nbsp;</span></span>\r\n"
				+ "<a href=\"/index.php?mid=gongji\" target=\"_parent\"><span style=\"FONT-SIZE: 11px\">공지사항</span></a>&nbsp;&nbsp;\r\n"
				+ "<a href=\"/index.php?mid=attendance\" target=\"_parent\"><span style=\"FONT-SIZE: 11px\">출석부</span></a>&nbsp;&nbsp;\r\n"
				+ "<a href=\"/index.php?mid=point_saving\" target=\"_parent\"><span style=\"FONT-SIZE: 11px\">활동지수적립소</span></a>&nbsp;&nbsp;\r\n"
				+ "<span style=\"COLOR: #fd6c46\"><span style=\"FONT-SIZE: 10px\">◀</span></span></div>\r\n"
				+ "<div id=\"gnb_event\"><p><img src=\"/image/total_title.gif\"><a href=\"/index.php?mid=challenge\" target=\"_parent\"><img src=\"/image/total_ehwjsrl.gif\" alt=\"자격증 도전기\"></a><a href=\"/index.php?mid=total_free\" target=\"_parent\"><img src=\"/image/total_wkdbrptlvks.gif\" alt=\"자유게시판\"></a><a href=\"/index.php?mid=total_hugi\" target=\"_parent\"><img src=\"/image/total_wkrurwmdgnrl.gif\" alt=\"자격증 시험후기\"></a><a href=\"/index.php?mid=licensepride\" target=\"_parent\"><img src=\"/image/total_Qhasorl.gif\" alt=\"자격증 뽐내기\"></a><a href=\"/index.php?mid=total_gija\" target=\"_parent\"><img src=\"/image/total_tnlsmstlrks.gif\" alt=\"스터디온 쉬는시간\"></a></p></div>\r\n"
				+ "<div id=\"gnb_event_temp1\"> </div>\r\n"
				+ "<div id=\"gnb_event_temp2\"> </div>\r\n"
				+ "<div id=\"gnb_event_temp3\"> </div>\r\n"
				+ "<div id=\"gnb_event_temp4\"> </div>\r\n"
				+ "<div id=\"gnb_event_temp5\"> </div>\r\n"
				+ "			<!-- 우측확장 -->\r\n"
				+ "<div id=\"add_right\"><p><img src=\"/image/rightmenu/tnlsmstlrks.gif\"></p>\r\n"
				+ "<p><a href=\"/index.php?mid=goodbook\" target=\"_parent\"><img src=\"/image/rightmenu/cncjsehtj.gif\" alt=\"추천도서\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=movie\" target=\"_parent\"><img src=\"/image/rightmenu/roqhddudghk.gif\" alt=\"개봉영화\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=cominfo\" target=\"_parent\"><img src=\"/image/rightmenu/zjavbxjtptkd.gif\" alt=\"컴퓨터세상\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=healthinfo\" target=\"_parent\"><img src=\"/image/rightmenu/rjsrkdwjdqh.gif\" alt=\"건강정보\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=starsnews\" target=\"_parent\"><img src=\"/image/rightmenu/dusdPdlswjdqh.gif\" alt=\"연예인정보\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=yeonhu\" target=\"_parent\"><img src=\"/image/rightmenu/rhtktjddj.gif\" alt=\"고사성어\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=imageroom\" target=\"_parent\"><img src=\"/image/rightmenu/dlalwl.gif\" alt=\"이미지모음\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=james\" target=\"_parent\"><img src=\"/image/rightmenu/dugodwjdqh.gif\" alt=\"여행정보\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=farmingdiary\" target=\"_parent\"><img src=\"/image/rightmenu/rnlshdtodghkf.gif\" alt=\"귀농생활\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=flashgame\" target=\"_parent\"><img src=\"/image/rightmenu/vmffotlrpdla.gif\" alt=\"플래시게임\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=mv\" target=\"_parent\"><img src=\"/image/rightmenu/abwlrqleldh.gif\" alt=\"뮤직비디오\"></a></p>\r\n"
				+ "<p><a href=\"/index.php?mid=ucc\" target=\"_parent\"><img src=\"/image/rightmenu/UCC.gif\" alt=\"UCC세상\"></a></p></div>\r\n"
				+ "			<!-- 검색폼 -->\r\n"
				+ "			<form action=\"https://www.studyon.co.kr/\" method=\"post\" id=\"isSearch\"><input type=\"hidden\" name=\"error_return_url\" value=\"/e0098\" />\r\n"
				+ "                <input type=\"hidden\" name=\"vid\" value=\"\" />\r\n"
				+ "                <input type=\"hidden\" name=\"mid\" value=\"e0098\" />\r\n"
				+ "                <input type=\"hidden\" name=\"act\" value=\"IS\" />\r\n"
				+ "                <input type=\"hidden\" name=\"search_target\" value=\"title_content\" />\r\n"
				+ "			<input name=\"is_keyword\" type=\"text\" title=\"Search\" class=\"inputText\" accesskey=\"S\" />\r\n"
				+ "			<input name=\"\" type=\"image\" src=\"/layouts/webmini 4.5.5/images/default/buttonSearch.gif\" alt=\"Search\" class=\"inputSearch\" />\r\n"
				+ "			</form>\r\n"
				+ "	</div>\r\n"
				+ "	<div id=\"contentBody\">\r\n"
				+ "		<div id=\"columnLeft\">\r\n"
				+ "			<!-- 좌측메뉴 -->\r\n"
				+ "<div class=\"xe-widget-wrapper \" style=\"\"><div style=\"*zoom:1;padding:0px 0px 0px 0px !important;\"><div class=\"widgetContainer\">\r\n"
				+ "<div class='title'>영사기능사 MENU</div>\r\n"
				+ "	<div class=\"widgetTree\">\r\n"
				+ "		<ul>\r\n"
				+ "		<li class=\"nav_tree_off\"><a href=\"/\"  class=\"nav_tree_label\">자격증전체보기(HOME)</a></li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105230\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=e0098\" class=\"nav_tree_label \" > 자격증시험정보</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105231\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=i_e0098\" class=\"nav_tree_label \" > 자격증소식</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105232\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=p1_e0098\" class=\"nav_tree_label \" > 필기기출문제</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105233\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=s1_e0098\" class=\"nav_tree_label \" > 실기기출문제</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105234\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=r_e0098\" class=\"nav_tree_label \" > 시험접수및가답안</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105235\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=m_e0098\" class=\"nav_tree_label \" > 추천교육</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105236\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=f_e0098\" class=\"nav_tree_label \" > 자유게시판</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105237\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=h_e0098\" class=\"nav_tree_label \" > 시험후기</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\" nav_tree_off\" id=\"menu_parent_3105238\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=t_e0098\" class=\"nav_tree_label \" > 시험자료공유</a>\r\n"
				+ "					</li>\r\n"
				+ "																	<li class=\"nav_tree_last nav_tree_off\" id=\"menu_parent_3105239\">\r\n"
				+ "		\r\n"
				+ "					\r\n"
				+ "		<a href=\"/index.php?mid=e_e0098\" class=\"nav_tree_label \" > CBT모의시험</a>\r\n"
				+ "					</li>\r\n"
				+ "												<li class=\"nav_tree_off\"><a href=\"/index.php?mid=point_saving\" class=\"nav_tree_label\">활동지수적립소</a></li>\r\n"
				+ "		</ul>\r\n"
				+ "	</div>\r\n"
				+ "</div>\r\n"
				+ "</div></div>\r\n"
				+ " \r\n"
				+ " \r\n"
				+ "			<!-- 뷰어다운 -->\r\n"
				+ "<div style=\"border:1px solid #dedede\">\r\n"
				+ "<p><img src=\"/image/viewerdown.gif\"></p>\r\n"
				+ "<p><a href=\"https://www.hancom.com/cs_center/csDownload.do\" target=\"_blank\"><img src=\"/image/hanglviewer.gif\"></a>\r\n"
				+ "<a href=\"https://get.adobe.com/kr/reader/\" target=\"_blank\"><img src=\"/image/adobeviewer.gif\"></a></p></div><br />\r\n"
				+ "			<!-- 스터디온뉴스 -->\r\n"
				+ "<div style=\"border:1px solid #dedede\">\r\n"
				+ "<p>&nbsp;&nbsp;<img src=\"/image/news/examdate.gif\" VSPACE=7></p>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?document_srl=3432339&mid=examschedule\" target=\"_parent\"><img src=\"/image/news/rltnftk.gif\" alt=\"기술사 시험일정\" align=\"left\" HSPACE=10> [국가자격증 시험일정]<br />&nbsp;&nbsp;2021년 기술사 시험일정</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?document_srl=3432368&mid=examschedule\" target=\"_parent\"><img src=\"/image/news/rltk.gif\" alt=\"기사 시험일정\" align=\"left\" HSPACE=10> [국가자격증 시험일정]<br />&nbsp;&nbsp;2021년 기사 시험일정</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?document_srl=3432412&mid=examschedule\" target=\"_parent\"><img src=\"/image/news/tksdjqrltk.gif\" alt=\"산업기사 시험일정\" align=\"left\" HSPACE=10> [국가자격증 시험일정]<br />&nbsp;&nbsp;2021년 산업기사 시험일정</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?document_srl=3432427&mid=examschedule\" target=\"_parent\"><img src=\"/image/news/rlsmdwkd.gif\" alt=\"기능장 시험일정\" align=\"left\" HSPACE=10> [국가자격증 시험일정]<br />&nbsp;&nbsp;2021년 기능장 시험일정</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?document_srl=3432442&mid=examschedule\" target=\"_parent\"><img src=\"/image/news/rlsmdtk.gif\" alt=\"기능사 시험일정\" align=\"left\" HSPACE=10> [국가자격증 시험일정]<br />&nbsp;&nbsp;2021년 기능사 시험일정</a></tbody></table>\r\n"
				+ "</div><br />\r\n"
				+ "<div style=\"border:1px solid #dedede\">\r\n"
				+ "<p>&nbsp;&nbsp;<img src=\"/image/news/chal_logo.gif\" VSPACE=7></p>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=e0128_ggnkal\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 전산응용건축제도기능사<br />&nbsp;&nbsp;실기 (by.꿈꾸는코알라)</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=b0090_bar\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 초음파비파괴검사기사<br />&nbsp;&nbsp;필기 (by.병아리님)</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=e0002_hgcns\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 가스기능사 필기<br />&nbsp;&nbsp;(by.화공초년생)</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=b0093_sty\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 침투비파괴검사기사 필기<br />&nbsp;&nbsp;(by.산타요님)</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=mrgcso01\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 전기공사기사 실기<br />&nbsp;&nbsp;(by.견초식음님)</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=mrgcso\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 전기기사 실기<br />&nbsp;&nbsp;(by.견초식음님)</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=mrgs\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 전기공사기사 필기<br />&nbsp;&nbsp;(by.겨울소나무님)</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=mrsgsdi\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 용접산업기사 실기<br />&nbsp;&nbsp;(by.쌍기사돌이님)</a></tbody></table>\r\n"
				+ "<table height=\"5\" cellSpacing=\"0\" cellPadding=\"0\" width=\"198\" border=\"0\"><tbody><a href=\"/index.php?mid=mrbc\" target=\"_parent\"><img src=\"/image/news/news_djg.gif\" align=\"left\" HSPACE=10>· 정보통신기사 실기<br />&nbsp;&nbsp;(by.병찬님)</a></tbody></table></div><br />\r\n"
				+ "			<!-- 고객센터 -->\r\n"
				+ "<div style=\"border:1px solid #dedede\">\r\n"
				+ "<center><a href=\"/index.php?mid=new_customer\" target=\"_blank\">\r\n"
				+ "<img src=\"/image/marketing/edu_qna.gif\"></a></div><br />\r\n"
				+ "<div style=\"border:1px solid #dedede\"><a href=\"https://www.facebook.com/studyonface/\" target=\"_blank\">\r\n"
				+ "<img src=\"/image/stydyon_facebook_go.jpg\"></a></center>\r\n"
				+ "<br />\r\n"
				+ "<br />\r\n"
				+ "<script async src=\"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"></script>\r\n"
				+ "<!-- 2020_웹좌측사이드광고 -->\r\n"
				+ "<ins class=\"adsbygoogle\"\r\n"
				+ "     style=\"display:inline-block;width:195px;height:163px\"\r\n"
				+ "     data-ad-client=\"ca-pub-0991599257318081\"\r\n"
				+ "     data-ad-slot=\"2686113527\"></ins>\r\n"
				+ "<script>\r\n"
				+ "     (adsbygoogle = window.adsbygoogle || []).push({});\r\n"
				+ "</script></div>\r\n"
				+ "		</div>\r\n"
				+ "		<div id=\"columnRight\">\r\n"
				+ "			<!-- 상단베너 -->\r\n"
				+ "<table height=\"104\" cellSpacing=\"0\" cellPadding=\"0\" width=\"100%\" border=\"0\">\r\n"
				+ "<tbody>\r\n"
				+ "<tr>\r\n"
				+ "<td style=\"PADDING-LEFT: 0px; PADDING-TOP: 0px\" valign=\"middle\" align=\"center\">\r\n"
				+ "<a href=\"https://bit.ly/3D4Ascw\" target=\"_blank\">\r\n"
				+ "<img src=\"/image/banner/hyeminwon_1220.jpg\"></a>\r\n"
				+ "</td></tr></tbody></table>\r\n"
				+ "<br />			<!-- 컨텐츠 시작 -->\r\n"
				+ "			<div class=\"xe_content xe-widget-wrapper \" style=\"FLOAT: left; WIDTH: 100%\"><div style=\"padding:0px 0px 0px 0px !important;\"><div class=\"kae\">\r\n"
				+ "    <div class=\"widhead\">\r\n"
				+ "        <div class=\"bg\">\r\n"
				+ "        	<h1>영사기능사 시험정보</h1>\r\n"
				+ "        </div>\r\n"
				+ "        <div class=\"more\">\r\n"
				+ "        	<a href=\"\"></a>\r\n"
				+ "        </div>\r\n"
				+ "    </div>\r\n"
				+ "    <div class=\"widcontent\">\r\n"
				+ "    	<p>&nbsp;</p>\r\n"
				+ "\r\n"
				+ "<p>&nbsp;문화적 컨텐츠의 종합예술 중 하나인 영화는 연속적인 영상이 필름 등의 매체에 담긴 유성 또는 무성의 영상물이기 때문에 관객이 이를 관람하기 위해서는 각종 영사기 조작을 통해 영상과 음향이 정확히 전달되어야 합니다.이에 따라 영사기 조작과 극장영상전달 시스템에 대한 전반적인 전문기술능력을 보유해야 합니다. 영화 상영 전 필름 및 디지털 매체, 영사기, 녹음재생장비를 조작하여 영화를 상영하며 상영 후 필름 되감기, 손상된 필름 수선, 영사장비점검 등이 주요 수행임.</p>\r\n"
				+ "\r\n"
				+ "<p><br />\r\n"
				+ "<strong>&lt;영사기능사 시험일정&gt;</strong></p>\r\n"
				+ "\r\n"
				+ "<p><img alt=\"시험일정\" src=\"/image/examdate/영사기능사시험일정.png\" /></p>\r\n"
				+ "\r\n"
				+ "<p><br />\r\n"
				+ "1. 시행처<br />\r\n"
				+ "&nbsp;&nbsp; 영화진흥위원회</p>\r\n"
				+ "\r\n"
				+ "<p><br />\r\n"
				+ "2. 시험과목<br />\r\n"
				+ "&nbsp;&nbsp; - 필기 : 1.전기일반 2.렌즈 및 광원 3.증폭기 및 녹음재생 4. 영사기와 필름의 구조원리<br />\r\n"
				+ "&nbsp;&nbsp; - 실기 : 영사작업</p>\r\n"
				+ "\r\n"
				+ "<p><br />\r\n"
				+ "3. 검정방법<br />\r\n"
				+ "&nbsp;&nbsp; - 필기 : 객관식 60문항(총 60분)<br />\r\n"
				+ "&nbsp;&nbsp; - 실기 : 작업형(30분 정도)</p>\r\n"
				+ "\r\n"
				+ "<p><br />\r\n"
				+ "4. 합격기준<br />\r\n"
				+ "&nbsp;&nbsp; - 필기&middot;실기 : 100점을 만점으로 하여 60점이상</p>\r\n"
				+ "\r\n"
				+ "<p><br />\r\n"
				+ "5. 검정수수료&nbsp;&nbsp;<br />\r\n"
				+ "&nbsp;&nbsp; 필기 : 11000원<br />\r\n"
				+ "&nbsp;&nbsp; 실기 : 47600원</p>\r\n"
				+ "\r\n"
				+ "<p>&nbsp;</p>\r\n"
				+ "\r\n"
				+ "<table align=\"right\" cellspacing=\"1\" style=\"BACKGROUND: #000000\">\r\n"
				+ "	<tbody>\r\n"
				+ "		<tr style=\"BACKGROUND: #000000\">\r\n"
				+ "			<td>\r\n"
				+ "			<p align=\"left\"><span style=\"COLOR: #ffffff\">?<span style=\"COLOR: #ffffff\"> 정보제공 : </span><a href=\"http://www.enap.or.kr/\" target=\"_blank\"><span style=\"COLOR: #ffffff\">영화진흥위원회</span></a><span style=\"COLOR: #ffffff\">&nbsp; </span></span></p>\r\n"
				+ "\r\n"
				+ "			<p align=\"left\"><span style=\"COLOR: #ffffff\">&nbsp;ⓒ 게시물작성 : <a href=\"gongji/335785\" target=\"_blank\"><span style=\"COLOR: #ffffff\">스터디온</span></a>&nbsp;</span></p>\r\n"
				+ "			</td>\r\n"
				+ "		</tr>\r\n"
				+ "	</tbody>\r\n"
				+ "</table>\r\n"
				+ "\r\n"
				+ "<p>&nbsp;</p>\r\n"
				+ "\r\n"
				+ "<p>&nbsp;</p>    </div>\r\n"
				+ "</div></div></div>		</div>\r\n"
				+ "	</div>\r\n"
				+ " \r\n"
				+ "<!-- /LNB -->\r\n"
				+ "	<div id=\"footer\">\r\n"
				+ "		<ul>\r\n"
				+ "						<li><a href=\"https://www.studyon.co.kr/index.php?mid=privacy\"  title=\"개인정보취급방침\">개인정보취급방침</a></li>\r\n"
				+ "						<li><a href=\"https://www.studyon.co.kr/index.php?mid=new_jongmok\"  title=\"신설자격증\">신설자격증</a></li>\r\n"
				+ "						<li><a href=\"https://www.studyon.co.kr/index.php?mid=new_stipulation\"  title=\"이용약관\">이용약관</a></li>\r\n"
				+ "						<li><a href=\"https://www.studyon.co.kr/index.php?mid=new_collection\"  title=\"이메일무단수집거부\">이메일무단수집거부</a></li>\r\n"
				+ "						<li><a href=\"https://www.studyon.co.kr/index.php?mid=sitemap\"  title=\"사이트맵\">사이트맵</a></li>\r\n"
				+ "						<li><a href=\"https://www.studyon.co.kr/index.php?mid=new_customer\"  title=\"광고문의\">광고문의</a></li>\r\n"
				+ "					</ul>\r\n"
				+ "         <p><a href=\"/index.php?document_srl=335785&mid=gongji\" target=\"_blank\">&copy; 스터디온 홈페이지와 모든 게시물은 저작권법 53조에 의거하여 보호받고 있습니다.</a></p>\r\n"
				+ "<p><font color=\"#3b3e45\"><span style=\"FONT-SIZE: 11px\">상호 : 스터디온커뮤니케이션&nbsp;&nbsp;&nbsp;&nbsp;대표자 : 신용철&nbsp;&nbsp;&nbsp;&nbsp;이메일 : studyoncokr@naver.com</span></font></p>\r\n"
				+ "<p><font color=\"#3b3e45\"><span style=\"FONT-SIZE: 11px\">\r\n"
				+ "Copyright &copy; 2008-2020 Studyon Communication Corporation All Rights Reserved.</span></font></p>	</div>\r\n"
				+ "</div><!-- ETC -->\r\n"
				+ "<div class=\"wfsr\"></div>\r\n"
				+ "<script src=\"/addons/autolink/autolink.js?20170416145618\"></script><script src=\"/common/js/plugins/ui/jquery-ui.min.js?20170313115619\"></script><script src=\"/common/js/plugins/ui/jquery.ui.datepicker-ko.js?20170313115619\"></script><script src=\"/addons/resize_image/js/resize_image.js?20170416145618\"></script><script src=\"/files/cache/js_filter_compiled/40a42b013db1786bcc1941f438e34407.ko.compiled.js?20201206234154\"></script><script src=\"/files/cache/js_filter_compiled/fa4b69aa483657fa3259290f341cb346.ko.compiled.js?20201206234154\"></script></body>\r\n"
				+ "</html>\r\n";
		try {
			Document doc = Jsoup.parse(html);
			
			Elements info = doc.select("div.bg");
			Elements schedule = doc.select("div.widcontent strong");
			String schedule2 = schedule.text().toString();
			schedule2 = schedule2.substring(1, schedule2.length()-1); // 시험일정 앞뒤 <>자르기

			Elements img = doc.select("div.widcontent img");
			Elements detail = doc.select("div.widcontent");
			String content = detail.html().toString();
			String info2 = content;
//			for(int i=0; i<info.size();i++) {
//				System.out.println(info.get(i).text());
//				System.out.println(schedule2);
//				System.out.println("https://www.studyon.co.kr/" + img.get(i).attr("src"));
//				
//			}
			System.out.println(info.text());
			info2 = info2.substring(0, info2.indexOf("<strong>"));
			System.out.println(info2);
			System.out.println(schedule2);
			System.out.println("https://www.studyon.co.kr/" + img.attr("src"));
			System.out.println("상세설명");

			
//			ht = ht.substring(ht.indexOf("<p><br> 1. 시행처"), ht.indexOf("?")); ?
			content = content.substring(content.indexOf("<p><br> 1."), content.indexOf("<table"));
//			ht = ht.substring(0, ht.indexOf("<p>&nbsp;</p>"));	?
			
			System.out.println(content);		
			// 시험 정보 / 정보내용 / 시험일정 / 일정 이미지 / 내용 /
			
		} catch (Exception e) {
			// TODO: handle exception
		}
	}

}
